kind: Deployment
apiVersion: apps/v1
metadata:
   name: wahib
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: wahib
   template:
      metadata:
        labels:
          app: wahib
      spec:
       containers:
        - name: wahib
          image: wahibx/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80
